// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['TagServiceImpl']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['TagServiceImpl']['Delete'](arg1);
}

export function List(arg1, arg2, arg3) {
  return window['go']['services']['TagServiceImpl']['List'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['services']['TagServiceImpl']['Start'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['TagServiceImpl']['Update'](arg1, arg2);
}
