// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function Create(arg1:string):Promise<types.JSResp>;

export function Delete(arg1:number):Promise<types.JSResp>;

export function List(arg1:number,arg2:number,arg3:string):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;

export function Update(arg1:number,arg2:string):Promise<types.JSResp>;
